In [2]:
import scipy.io
import matplotlib.pyplot as plt


In [3]:
mat_data = scipy.io.loadmat(r"C:\Users\ratho\Desktop\Software Group Project - III\Climate Data Modelling\RIDDHI\old_code_summer_internship_may2020\category_rain.mat")
mat_data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Tue Sep 08 19:16:30 2020',
 '__version__': '1.0',
 '__globals__': [],
 'category_rain': array([[4, 4, 3, 4, 4, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 3, 4],
        [4, 4, 4, 4, 3, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 3, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 3, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 5, 4, 4, 4, 4],
        [4, 3, 4, 4, 4, 4],
        [4, 4, 4, 4, 3, 4],
        [4, 4, 4, 4, 3, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 4, 6, 4, 4, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 4, 5, 4, 4, 4],
        [4, 4, 4, 4, 3, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 5, 4],
        [4, 4, 4, 4, 5, 4],
    

In [3]:
mat_data.keys()

dict_keys(['__header__', '__version__', '__globals__', 'category_rain'])

In [4]:
ss=mat_data['category_rain']

In [5]:
ss.shape

(108, 4)

In [6]:
ss

array([[4, 4, 3, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 3, 4],
       [4, 4, 4, 4, 3, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 3, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 3, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 5, 4, 4, 4, 4],
       [4, 3, 4, 4, 4, 4],
       [4, 4, 4, 4, 3, 4],
       [4, 4, 4, 4, 3, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 6, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 5, 4, 4, 4],
       [4, 4, 4, 4, 3, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 5, 4],
       [4, 4, 4, 4, 5, 4],
       [4, 4, 4, 4, 6, 4],
       [4, 4, 4, 4, 6, 4],
       [4, 4, 4, 4, 5, 4],
       [4, 4, 4, 4, 6, 4],
       [4, 4, 4, 4, 6, 4],
       [4, 4, 6, 4, 6, 4],
       [4, 4, 4, 4, 5, 4],
 

In [10]:
def PlotMap(data,year=0):
    # Create a figure and axis for the plot
    fig, ax = plt.subplots()

    # Create a colormap
    cmap = plt.get_cmap('rainbow')  # You can choose any other colormap you prefer

    # Determine the appropriate color limits based on your data
    vmin = 0.0  # Minimum value for the color scale
    vmax = 10.0  # Maximum value for the color scale

    # Plot the average yearly rainfall data using the colormap
    im = ax.imshow(data, cmap=cmap, vmin=vmin, vmax=vmax, origin='lower',
                   extent=[data['lon'].min(), data['lon'].max(),
                           data['lat'].min(), data['lat'].max()])

    # Add colorbar
    cbar = plt.colorbar(im, ax=ax, label='Rainfall')

    # Set axis labels
    ax.set_xlabel('Longitude')
    ax.set_ylabel('Latitude')
    ax.set_title(f'Average Yearly Rainfall Data of {year} from June to September')

In [26]:
# plt.imshow(ss[1], cmap='magma') 
ss[0][0][0] 

array([-999., -999., -999., -999., -999., -999., -999., -999., -999.,
       -999., -999., -999., -999., -999., -999., -999.])

In [13]:
import numpy as np
np.set_printoptions(threshold=np.inf, linewidth=np.inf)
ss[0][99]

array([[-9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02],
       [-9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02],
       [-9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02],
       [-9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02],
       [-9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02],
       [-9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -9.99e+02, -